INSERT INTO Users (first_name, last_name, email) VALUES ('Tony', 'Smith', 'tony@example.com');
INSERT INTO Products (product_name, product_description, product_price) VALUES ('Red Shoes', 'Vintage red shoes.', 59.99);
INSERT INTO Categories (category_name) VALUES ('Shoes');
INSERT INTO Product_Categories (product_id, category_id) VALUES (1, 1);
INSERT INTO Orders (user_id) VALUES (1);
INSERT INTO Order_Details (order_id, product_id, quantity) VALUES (1, 1, 2);
INSERT INTO Shipping_Methods (method_name, shipping_cost, shipping_time) VALUES ('Express', 10.00, '2 days');
INSERT INTO Addresses (user_id, address_line1, city, state, postal_code, country) VALUES (1, '123 Main St', 'Denver', 'CO', '80120', 'USA');
INSERT INTO Payments (user_id, card_number, expiration_date) VALUES (1, '1234123412341234', '2026-04-04');
INSERT INTO Invoices (order_id, user_id, payment_id) VALUES (1, 1, 1);