UPDATE Users SET first_name='Stalone' WHERE user_id=1;
UPDATE Products SET product_price=69.99 WHERE product_id=1;
UPDATE Categories SET category_name='Shirts' WHERE category_id=1;
UPDATE Order_Details SET quantity=3 WHERE order_id=1 AND product_id=1;
UPDATE Shipping_Methods SET shipping_cost=12.00 WHERE shipping_id=1;
UPDATE Addresses SET city='Chicago' WHERE address_id=1;
UPDATE Payments SET card_number='4321432143214321' WHERE payment_id=1;
UPDATE Invoices SET user_id=2 WHERE invoice_id=1;
UPDATE Inventory SET stock=20 WHERE inventory_id=1;
UPDATE Reviews SET rating=4 WHERE review_id=1;